# Generated by Django 3.2.9 on 2021-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('item', models.CharField(max_length=2000)),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
